#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{bm}

#+begin_verse
Maurizio Ferrari
Handling Editor
Optical Materials
#+end_verse

Dear Dr. Ferrari,

In the following we comment on the referee's remarks and on the
corresponding changes we performed on our manuscript Ref. No.:  OM-D-20-02614,
/Model of the Current Density in the Electrochemical Synthesis of PS/
/Structures with a Lateral Gradient/ submitted to /Optical Materials/.

1. The paper reports about the modelisation allowing to calculate the
   etching current density applied in each point of a silicon
   substrate to synthesize porous silicon layers with lateral gradient
   by electrochemical anodisation. The electrode is a wire immersed in
   a prism shaped electrolytic cell.

   The experimental reflectance spectra obtained at different
   locations of the porous layer are adjusted to the theoretical
   spectra in order to determine the porosity of the layer locally,
   the thickness of the layer being determined by scanning electron
   microscopy. The etching rate and the porosity are thus determined
   at different positions for each porous silicon layer studied.

   For each sample studied, calibration curves of variation of
   porosity and etching rate of the porous layers, obtained with this
   device, and plotted against the current density calculated by the
   proposed model, are presented and more or less
   coincide. Theoretical reflectance spectra are also calculated and
   agree with the experimental spectra. These calibration curves are
   specific to this device and can be used to fabricate more complex
   multilayer structures with porosity gradient and to study their
   optical properties.  The authors thus evaluate with their model the
   gradient of lateral porosity and etching speed, which is very
   important for porous silicon applications.

   For my point of view, the article presents interesting results in
   the topic of the journal. Quality of the research is suitable for the
   journal. The article is quite well detailed and so
   comprehensible. However, revision considering the following comments
   is necessary before publication.

   - We appreciate the summary of our work by the reviewer and we are
     grateful for his opinion.

   - As discussed below, the thickness of the layers was not
     determined through scanning electron microscopy (see below).

2. Since Figure 4 is composed of 3 parts, the authors should
   distinguish them by fig.4a, 4b and 4.c.

   - We have labelled the panels of figure 4 as (a), (b) and (c) and
     as such refered to their content in the corresponding caption.

3. Figures 4b and 4c, already represent the porosity gradient and the
   etching rate of the silicon in a top and a side view of a porous
   silicon sample . From my point of view, these are results, and
   figure 4 could be put in the results section and discussed with
   figure 6 . Even the current lines in figure 4a should be given in
   the results part in confrontation to Figure 6.

   - Figures 4b and 4c are /schematic drawings/ to illustrate what are
     the /expected/ results, but they are not results obtained through
     a theoretical calculation nor from experimental
     measurements. Thus we believe that the reader might be misled if
     we move them to the results section. For this reason, we prefer
     to leave at their previous place.

4. in the "procedure" part, it must be specified that the thickness
   has been determined by microscopic observation and that the
   reflectance spectra can then be adjusted to determine the porosity
   P

   - We actually did not determine the thickness through microscopic
     observations. We obtained /both/ the porosity /and/ the thickness
     from and adjustment to the optical spectra.

   - The SEM images shown in Figure 7 verify /qualitatively/ our
     expected results (Figure 4) and our adjusted results (Table 2),
     but were not used to measure the actual thickness of the
     sample at the positions $n$ where we measured the optical
     spectra. That was not possible as in order to obtain the
     micrographs we had to cut the sample.

   - We modified the text where we present Fig. 7 to eliminate any
     confusion about this issue.

5. in the current density part : "In Fig. 5 we show the current
   density j_\perp(x,y , 0) calculated through Eq. (16) at the surface of
   the sample for our cell, as shown in Figs. 1 and 4 and described in
   Sect. 3.1)."the authors should precise in the text: normalized
   current density J /I .

   - We agree with the reviewer and we performed the suggested change.

6. The authors should another letter than G1, G2 G3 to name their
   samples as G is used in the model to represent the 2D reciprocal
   lattice.

   - We used Gn to label samples as it stands for GRIN-n, but we agree
     with the reviewer and changed the labels to Sn, where S stands
     for Sample. We modified the text, some figures and figure
     captions to include this change.

7. in the text " "From the data in Table 2 we can plot the fitted
   porosity as a function of the calculated density current, as shown
   for our three samples in Fig. 11."the authors should precise the
   used equation, in reference to their model.
   - We notice that our original wording might have produced some
     confusion. The porosity together with the thickness were /fitted/
     to optical measurements using Eqs. (18) and (19). These equations
     are mentioned explicitly in the first lines of Sect. 4.3.
   - Thus, what we show in Fig. 11 as data points are those previously
     fitted porosity values vs. the computed current density.
     When we mentioned that 'we can plot the fitted porosity as a
     function of the calculated density current' we didn't use any
     other equation.
   - We believe that the confusion may be eliminated by rewording the
     phrase 'porosity as a function of the calculated density current'
     and rewrite it as 'porosity vs. calculated density current',
     i.e., by eliminating the word 'function'.
   - Nevertheless, a few lines afterwards we introduce a new fit: we
     fit the porosity as a function of the current density. To that
     end we use a linear fit of the kind $p=mj_\perp+b$ and we display
     the parameters $m$ and $b$ at the top of Fig. 11 and in Eq. (20).
   - To clear up this second fit, following the reviewers advice, we
     wrote down explicitly the equation for this linear fit.
   - We made similar changes regarding Fig. 12.
8. Could the authors more explain the sentence "For multilayered
   samples, produced by modulating the current I in time, without
   changing wafers, these error source would be absent."

   - The horizontal position of the points in Figs. 11 and 12, the current
     density, was calculated using our theory (Eq. (16)) at the
     positions $x_n$ (with respect to the wall of the cell) for which we
     measured the reflectance spectrum, but these positions are
     uncertain, as what we measured were the distances $x'_n$ to the
     edge of the chemically attacked region. We prepared different
     layers by applying different currents to different samples, but a
     multilayered system is made by applying a time varying current to
     a single sample. The quantities $x'_n-x_n$
     might differ for layers built on different wafers, but not for
     those prepared on a single wafer.

   - We rephrased that sentence in order to make our meaning clear.

9. In table 2 the authors should estimate the uncertainties of their
    results and show the uncertainties on the curves in Figures 11
    and 12. To my opinion, only one general fit should be used as  it
    depends on the current densities.

   - We agree with the referee.

   - We included the error estimates in
     table 1 due to the position uncertainties.

   - We made new fits to the reflectance data using a different
     optimization algorithm, so that we could obtain an uncertainty
     for the fitted parameters.

   - We changed figures 8-10 using the new fits.

   - We modified table 2 to include the new parameters and their uncertainties.

10. The results should be more discussed with taking into consideration the uncertainties.

    - We incorporated a discussion of the uncertainty in all
      parameters.

11. "Furthermore, as the results corresponding to sample G2 in Figs. 11
    and 12 seem shifted with respect to those of the other samples," How
    do the authors explain the shift for the sample G2 in fig 11 and fig
    12 ?
    - Due to the ill defined edge of the sample (the beginning of the
      chemically attacked region), it is possible that
      the positions where we measured the reflectance spectra for
      sample S2 correspond to larger distances from the edge of the
      wall than those reported in table 1 and used to compute the
      current density. We estimated an uncertainty in position of half
      a millimeter, corresponding to the radius of the sealing o-ring,
      but it could have been larger. Through a rigid displacement of
      the sample (adding a constant to all $x_n$'s for sample 2), its
      results could be brought into better agreement with the
      other samples, and both figures are consistent with a correction
      in the same direction. Nevertheless, given the uncertainty in
      the fitted parameters, we believe it is better to present the
      results as they were obtained.

12. the model is performed for a wire electrode. What is the tendency if
    using a planar electrode on the side, or on the top?
	  In many applications using porous silicon , homogenous
    porosity as well as etching rate is also required.
	   How is it possible the reduce the porosity gradient in a
    porous silicon  sample?

    - There are many techniques to produce relatively homogeneous
      porous silicon samples. One could use planar electrodes, or
      immerse in the electrolyte long non-insulated wire electrodes
      bent into shapes such as a spiral that covers a relatively large
      area. However, our purpose in this paper is the
      opposite; to produce a sizable gradient in porous silicon
      structures but in a controlled way. We showed that for a
      particular shape and for a thin wire insulated except in a very
      small region, the etching current may be obtained as a rapidly
      converging sum each of whose terms can be calculated
      analytically. Thus, we can easily predict the current density and use
      this prediction to calibrate the etching process and to design
      gradient structures.

13. the part "discussion and result" should be renamed by result and discussions
    1. Indeed. Done.

14. References 7 and 8 have to be checked in "synthesis of Ag-Au alloy
    gradients on steel and chemical composition gradients of CdS
    layers on gold electrodes have also been obtained [7]. Among
    electrochemical methods, compositional and doping density changes
    in conducting polymers have been used to produce gradients using
    Indium Tin Oxide electrodes [8].". [ref 7] is OK in "Recently, J
    Wang et al. has shown the fabrication of a miniature spectrometer
    with a PS based rugate filter using a radial interfacial potential
    distribution [7]."

15. Other references should be added to the reference  12 -for the
    biosensing Porous silicon application in "Applications based on
    porous silicon now cover various fields such as chemical sensors
    and biosensors [12]".

16. Other references should be added with the reference 15 to
    illustrate optoelectronics applications: "microelectronics and
    micromechanical systems (MEMS) [13],as well as a range of optical
    [14] and optoelectronic applications [15]."

17. The authors should give more references for the porous silicon
    multilayered structures : waveguide, Bragg reflector,
    Microcavities, Microresonator  "Specifically, the temporal
    variation of the current density results in a variation of porosity
    along the depth, allowing the easy fabrication of different kinds
    [16] of 1D dielectric multilayered structures." .

18. The reference 19 is not adapted ".The resulting porous surface can
    have pore sizes ranging from a few nanometers to few micrometers
    [19]."

19. Many typo errors have to be corrected
    - We corrected several typo errors.

20. The quality text should be improved. The authors should use the passive form instead of we….
    - We prefer the use of the active form over the passive form, as it
      yields simpler easier to follow texts. We would be glad to change
      our manuscript to the passive voice if required.

In summary, we have addressed all of the reviewers comments and acted on
most of his recommendations. We believe that, as stated by the
reviewer, that the paper contains interesting results of
suitable quality, they are presented with enough detail and so they
should be of interest to the readership of the journal.


Yours truly,

W: Luis Mochán
